[build]
  command = "npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://your-api-url.com"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyA8MFoP8ZJNft4SXTZ4vR9nOEYz35hB5MY"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:347323668810:web:d28cff23d9b3e1f908c9b3"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "smskeychain"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY = "sk_test_51RCcI7R8HFJ6dkRaN6pakizFAOdsj0IAkXWyu1rpouHlGwE6c4fV0OOpi8bpmWQXSYfFbE7Ls2VVWfk4SbSG8tre00TtiHHAC4"
  DATABASE_URL = "postgresql://neondb_owner:npg_1eZGHxTFVM9w@ep-curly-firefly-a4a4yys8-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
  PGDATABASE = "neondb"
  PGHOST = "ep-curly-firefly-a4a4yys8-pooler.us-east-1.aws.neon.tech"
  PGPORT = "5432"
  PGUSER = "neondb_owner"
  PGPASSWORD = "npg_1eZGHxTFVM9w"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 